require:
  - rubocop-performance
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
   - 'db/migrate/**.rb'

Layout/LineLength:
  Max: 100
  Exclude:
   - 'db/seeds.rb'

Style/AccessorGrouping:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Naming/RescuedExceptionsVariableName:
  PreferredName: 'exception'

Style/FormatStringToken:
  EnforcedStyle: template

RSpec:
  Exclude:
    - 'spec/factories/**/*'

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Enabled: false

# while that is a good rule, AR objects can't be properly instance_double'd
RSpec/VerifiedDoubles:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'docker/**/*'
    - 'doc/**/*'
    - 'bin/**/*'
    - 'Rakefile'
    - 'config.ru'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
