version: '3'
services:
  postgresql:
    image: "postgres:12.5"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      ALLOW_IP_RANGE: 0.0.0.0/0
